action_dim: ???
action_dims: ???
batch_size: 256
bin_size: ???
buffer_size: 1000000
checkpoint: ???
compile: true
consistency_coef: 20
data_dir: ???
discount_denom: 5
discount_max: 0.995
discount_min: 0.95
dropout: 0.01
enable_wandb: true
enc_dim: 256
enc_lr_scale: 0.3
entropy_coef: 1e-4
episode_length: ???
episode_lengths: ???
episodic: false
eval_episodes: 10
eval_freq: 50000
exp_name: default
grad_clip_norm: 20
horizon: 3
ib_coef: 0.0
iterations: 6
latent_dim: 512
log_std_max: 2
log_std_min: -10
lr: 3e-4
max_std: 2
min_std: 0.05
mlp_dim: 512
model_size: ???
mpc: true
multitask: ???
num_bins: 101
num_channels: 32
num_elites: 64
num_enc_layers: 2
num_pi_trajs: 24
num_q: 5
num_samples: 512
obs: state
obs_shape: ???
obs_shapes: ???
reward_coef: 0.1
rho: 0.5
save_agent: true
save_csv: true
save_video: true
se_coef: 0.0
seed: 1
seed_steps: ???
simnorm_dim: 8
steps: 10000000
task: dog-run
task_dim: 96
task_title: ???
tasks: ???
tau: 0.01
temperature: 0.5
termination_coef: 1
value_coef: 0.1
vmax: 10
vmin: -10
wandb_entity: ???
wandb_project: ???
wandb_silent: false
work_dir: ???
